/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PTokenRouteImport } from './routes/p.$token'
import { Route as AuthenticatedFranchiseRouteImport } from './routes/_authenticated/franchise'
import { Route as AuthenticatedCompanyRouteImport } from './routes/_authenticated/company'
import { Route as AuthenticatedAppRouteImport } from './routes/_authenticated/app'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedFranchiseIndexRouteImport } from './routes/_authenticated/franchise.index'
import { Route as AuthenticatedCompanyIndexRouteImport } from './routes/_authenticated/company.index'
import { Route as AuthenticatedAppIndexRouteImport } from './routes/_authenticated/app.index'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin.index'
import { Route as AuthenticatedFranchiseMembersRouteImport } from './routes/_authenticated/franchise.members'
import { Route as AuthenticatedFranchiseCompaniesRouteImport } from './routes/_authenticated/franchise.companies'
import { Route as AuthenticatedFranchiseBillingRouteImport } from './routes/_authenticated/franchise.billing'
import { Route as AuthenticatedCompanyMembersRouteImport } from './routes/_authenticated/company.members'
import { Route as AuthenticatedCompanyLeadershipRouteImport } from './routes/_authenticated/company.leadership'
import { Route as AuthenticatedCompanyLeadersRouteImport } from './routes/_authenticated/company.leaders'
import { Route as AuthenticatedCompanyBillingRouteImport } from './routes/_authenticated/company.billing'
import { Route as AuthenticatedAppTeamRouteImport } from './routes/_authenticated/app.team'
import { Route as AuthenticatedAppPulsesRouteImport } from './routes/_authenticated/app.pulses'
import { Route as AuthenticatedAppPdisRouteImport } from './routes/_authenticated/app.pdis'
import { Route as AuthenticatedAppOrganizationRouteImport } from './routes/_authenticated/app.organization'
import { Route as AuthenticatedAppOneOnOnesRouteImport } from './routes/_authenticated/app.one-on-ones'
import { Route as AuthenticatedAppIndicatorsRouteImport } from './routes/_authenticated/app.indicators'
import { Route as AuthenticatedAppHelpRouteImport } from './routes/_authenticated/app.help'
import { Route as AuthenticatedAppFeedbacksRouteImport } from './routes/_authenticated/app.feedbacks'
import { Route as AuthenticatedAppEvolutionRouteImport } from './routes/_authenticated/app.evolution'
import { Route as AuthenticatedAppConscienciaRouteImport } from './routes/_authenticated/app.consciencia'
import { Route as AuthenticatedAppAiRouteImport } from './routes/_authenticated/app.ai'
import { Route as AuthenticatedApp360RouteImport } from './routes/_authenticated/app.360'
import { Route as AuthenticatedAdminUsersRouteImport } from './routes/_authenticated/admin.users'
import { Route as AuthenticatedAdminSubscriptionsRouteImport } from './routes/_authenticated/admin.subscriptions'
import { Route as AuthenticatedAdminSettingsRouteImport } from './routes/_authenticated/admin.settings'
import { Route as AuthenticatedAdminPlansRouteImport } from './routes/_authenticated/admin.plans'
import { Route as AuthenticatedAdminPermissionsRouteImport } from './routes/_authenticated/admin.permissions'
import { Route as AuthenticatedAdminOrganizationsRouteImport } from './routes/_authenticated/admin.organizations'
import { Route as AuthenticatedAdminOnboardingRouteImport } from './routes/_authenticated/admin.onboarding'
import { Route as AuthenticatedAdminNotificationsRouteImport } from './routes/_authenticated/admin.notifications'
import { Route as AuthenticatedAdminModulesRouteImport } from './routes/_authenticated/admin.modules'
import { Route as AuthenticatedAdminMethodologyRouteImport } from './routes/_authenticated/admin.methodology'
import { Route as AuthenticatedAdminLogsRouteImport } from './routes/_authenticated/admin.logs'
import { Route as AuthenticatedAdminLicensesRouteImport } from './routes/_authenticated/admin.licenses'
import { Route as AuthenticatedAdminInvoicesRouteImport } from './routes/_authenticated/admin.invoices'
import { Route as AuthenticatedAdminHierarchyRouteImport } from './routes/_authenticated/admin.hierarchy'
import { Route as AuthenticatedAdminHelpRouteImport } from './routes/_authenticated/admin.help'
import { Route as AuthenticatedAdminFranchisesRouteImport } from './routes/_authenticated/admin.franchises'
import { Route as AuthenticatedAdminDataRouteImport } from './routes/_authenticated/admin.data'
import { Route as AuthenticatedAdminBrandingRouteImport } from './routes/_authenticated/admin.branding'
import { Route as AuthenticatedAdminBillingRouteImport } from './routes/_authenticated/admin.billing'
import { Route as AuthenticatedAdminAppsRouteImport } from './routes/_authenticated/admin.apps'
import { Route as AuthenticatedAdminAiRouteImport } from './routes/_authenticated/admin.ai'
import { Route as AuthenticatedAppOrganizationIndexRouteImport } from './routes/_authenticated/app.organization.index'
import { Route as AuthenticatedAppTeamMembershipIdRouteImport } from './routes/_authenticated/app.team.$membershipId'
import { Route as AuthenticatedAppOrganizationRolesRouteImport } from './routes/_authenticated/app.organization.roles'
import { Route as AuthenticatedAppOrganizationRitualsRouteImport } from './routes/_authenticated/app.organization.rituals'
import { Route as AuthenticatedAppOrganizationMapRouteImport } from './routes/_authenticated/app.organization.map'
import { Route as AuthenticatedAppOrganizationDocumentsRouteImport } from './routes/_authenticated/app.organization.documents'
import { Route as AuthenticatedAppOrganizationDelegationsRouteImport } from './routes/_authenticated/app.organization.delegations'
import { Route as AuthenticatedAppOrganizationDecisionsRouteImport } from './routes/_authenticated/app.organization.decisions'
import { Route as AuthenticatedAppOrganizationCyclesRouteImport } from './routes/_authenticated/app.organization.cycles'
import { Route as AuthenticatedAppOrganizationAreasRouteImport } from './routes/_authenticated/app.organization.areas'
import { Route as AuthenticatedAppOrganizationAgendaRouteImport } from './routes/_authenticated/app.organization.agenda'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PTokenRoute = PTokenRouteImport.update({
  id: '/p/$token',
  path: '/p/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedFranchiseRoute = AuthenticatedFranchiseRouteImport.update({
  id: '/franchise',
  path: '/franchise',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCompanyRoute = AuthenticatedCompanyRouteImport.update({
  id: '/company',
  path: '/company',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAppRoute = AuthenticatedAppRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedFranchiseIndexRoute =
  AuthenticatedFranchiseIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedFranchiseRoute,
  } as any)
const AuthenticatedCompanyIndexRoute =
  AuthenticatedCompanyIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedAppIndexRoute = AuthenticatedAppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedFranchiseMembersRoute =
  AuthenticatedFranchiseMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedFranchiseRoute,
  } as any)
const AuthenticatedFranchiseCompaniesRoute =
  AuthenticatedFranchiseCompaniesRouteImport.update({
    id: '/companies',
    path: '/companies',
    getParentRoute: () => AuthenticatedFranchiseRoute,
  } as any)
const AuthenticatedFranchiseBillingRoute =
  AuthenticatedFranchiseBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedFranchiseRoute,
  } as any)
const AuthenticatedCompanyMembersRoute =
  AuthenticatedCompanyMembersRouteImport.update({
    id: '/members',
    path: '/members',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedCompanyLeadershipRoute =
  AuthenticatedCompanyLeadershipRouteImport.update({
    id: '/leadership',
    path: '/leadership',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedCompanyLeadersRoute =
  AuthenticatedCompanyLeadersRouteImport.update({
    id: '/leaders',
    path: '/leaders',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedCompanyBillingRoute =
  AuthenticatedCompanyBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedCompanyRoute,
  } as any)
const AuthenticatedAppTeamRoute = AuthenticatedAppTeamRouteImport.update({
  id: '/team',
  path: '/team',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPulsesRoute = AuthenticatedAppPulsesRouteImport.update({
  id: '/pulses',
  path: '/pulses',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppPdisRoute = AuthenticatedAppPdisRouteImport.update({
  id: '/pdis',
  path: '/pdis',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppOrganizationRoute =
  AuthenticatedAppOrganizationRouteImport.update({
    id: '/organization',
    path: '/organization',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppOneOnOnesRoute =
  AuthenticatedAppOneOnOnesRouteImport.update({
    id: '/one-on-ones',
    path: '/one-on-ones',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppIndicatorsRoute =
  AuthenticatedAppIndicatorsRouteImport.update({
    id: '/indicators',
    path: '/indicators',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppHelpRoute = AuthenticatedAppHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAppFeedbacksRoute =
  AuthenticatedAppFeedbacksRouteImport.update({
    id: '/feedbacks',
    path: '/feedbacks',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppEvolutionRoute =
  AuthenticatedAppEvolutionRouteImport.update({
    id: '/evolution',
    path: '/evolution',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppConscienciaRoute =
  AuthenticatedAppConscienciaRouteImport.update({
    id: '/consciencia',
    path: '/consciencia',
    getParentRoute: () => AuthenticatedAppRoute,
  } as any)
const AuthenticatedAppAiRoute = AuthenticatedAppAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedApp360Route = AuthenticatedApp360RouteImport.update({
  id: '/360',
  path: '/360',
  getParentRoute: () => AuthenticatedAppRoute,
} as any)
const AuthenticatedAdminUsersRoute = AuthenticatedAdminUsersRouteImport.update({
  id: '/users',
  path: '/users',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminSubscriptionsRoute =
  AuthenticatedAdminSubscriptionsRouteImport.update({
    id: '/subscriptions',
    path: '/subscriptions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSettingsRoute =
  AuthenticatedAdminSettingsRouteImport.update({
    id: '/settings',
    path: '/settings',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPlansRoute = AuthenticatedAdminPlansRouteImport.update({
  id: '/plans',
  path: '/plans',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminPermissionsRoute =
  AuthenticatedAdminPermissionsRouteImport.update({
    id: '/permissions',
    path: '/permissions',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOrganizationsRoute =
  AuthenticatedAdminOrganizationsRouteImport.update({
    id: '/organizations',
    path: '/organizations',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminOnboardingRoute =
  AuthenticatedAdminOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminNotificationsRoute =
  AuthenticatedAdminNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminModulesRoute =
  AuthenticatedAdminModulesRouteImport.update({
    id: '/modules',
    path: '/modules',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminMethodologyRoute =
  AuthenticatedAdminMethodologyRouteImport.update({
    id: '/methodology',
    path: '/methodology',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminLogsRoute = AuthenticatedAdminLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminLicensesRoute =
  AuthenticatedAdminLicensesRouteImport.update({
    id: '/licenses',
    path: '/licenses',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminInvoicesRoute =
  AuthenticatedAdminInvoicesRouteImport.update({
    id: '/invoices',
    path: '/invoices',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHierarchyRoute =
  AuthenticatedAdminHierarchyRouteImport.update({
    id: '/hierarchy',
    path: '/hierarchy',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminHelpRoute = AuthenticatedAdminHelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminFranchisesRoute =
  AuthenticatedAdminFranchisesRouteImport.update({
    id: '/franchises',
    path: '/franchises',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminDataRoute = AuthenticatedAdminDataRouteImport.update({
  id: '/data',
  path: '/data',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminBrandingRoute =
  AuthenticatedAdminBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminBillingRoute =
  AuthenticatedAdminBillingRouteImport.update({
    id: '/billing',
    path: '/billing',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAppsRoute = AuthenticatedAdminAppsRouteImport.update({
  id: '/apps',
  path: '/apps',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAdminAiRoute = AuthenticatedAdminAiRouteImport.update({
  id: '/ai',
  path: '/ai',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)
const AuthenticatedAppOrganizationIndexRoute =
  AuthenticatedAppOrganizationIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AuthenticatedAppOrganizationRoute,
  } as any)
const AuthenticatedAppTeamMembershipIdRoute =
  AuthenticatedAppTeamMembershipIdRouteImport.update({
    id: '/$membershipId',
    path: '/$membershipId',
    getParentRoute: () => AuthenticatedAppTeamRoute,
  } as any)
const AuthenticatedAppOrganizationRolesRoute =
  AuthenticatedAppOrganizationRolesRouteImport.update({
    id: '/roles',
    path: '/roles',
    getParentRoute: () => AuthenticatedAppOrganizationRoute,
  } as any)
const AuthenticatedAppOrganizationRitualsRoute =
  AuthenticatedAppOrganizationRitualsRouteImport.update({
    id: '/rituals',
    path: '/rituals',
    getParentRoute: () => AuthenticatedAppOrganizationRoute,
  } as any)
const AuthenticatedAppOrganizationMapRoute =
  AuthenticatedAppOrganizationMapRouteImport.update({
    id: '/map',
    path: '/map',
    getParentRoute: () => AuthenticatedAppOrganizationRoute,
  } as any)
const AuthenticatedAppOrganizationDocumentsRoute =
  AuthenticatedAppOrganizationDocumentsRouteImport.update({
    id: '/documents',
    path: '/documents',
    getParentRoute: () => AuthenticatedAppOrganizationRoute,
  } as any)
const AuthenticatedAppOrganizationDelegationsRoute =
  AuthenticatedAppOrganizationDelegationsRouteImport.update({
    id: '/delegations',
    path: '/delegations',
    getParentRoute: () => AuthenticatedAppOrganizationRoute,
  } as any)
const AuthenticatedAppOrganizationDecisionsRoute =
  AuthenticatedAppOrganizationDecisionsRouteImport.update({
    id: '/decisions',
    path: '/decisions',
    getParentRoute: () => AuthenticatedAppOrganizationRoute,
  } as any)
const AuthenticatedAppOrganizationCyclesRoute =
  AuthenticatedAppOrganizationCyclesRouteImport.update({
    id: '/cycles',
    path: '/cycles',
    getParentRoute: () => AuthenticatedAppOrganizationRoute,
  } as any)
const AuthenticatedAppOrganizationAreasRoute =
  AuthenticatedAppOrganizationAreasRouteImport.update({
    id: '/areas',
    path: '/areas',
    getParentRoute: () => AuthenticatedAppOrganizationRoute,
  } as any)
const AuthenticatedAppOrganizationAgendaRoute =
  AuthenticatedAppOrganizationAgendaRouteImport.update({
    id: '/agenda',
    path: '/agenda',
    getParentRoute: () => AuthenticatedAppOrganizationRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/app': typeof AuthenticatedAppRouteWithChildren
  '/company': typeof AuthenticatedCompanyRouteWithChildren
  '/franchise': typeof AuthenticatedFranchiseRouteWithChildren
  '/p/$token': typeof PTokenRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/apps': typeof AuthenticatedAdminAppsRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/branding': typeof AuthenticatedAdminBrandingRoute
  '/admin/data': typeof AuthenticatedAdminDataRoute
  '/admin/franchises': typeof AuthenticatedAdminFranchisesRoute
  '/admin/help': typeof AuthenticatedAdminHelpRoute
  '/admin/hierarchy': typeof AuthenticatedAdminHierarchyRoute
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/admin/licenses': typeof AuthenticatedAdminLicensesRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/methodology': typeof AuthenticatedAdminMethodologyRoute
  '/admin/modules': typeof AuthenticatedAdminModulesRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/onboarding': typeof AuthenticatedAdminOnboardingRoute
  '/admin/organizations': typeof AuthenticatedAdminOrganizationsRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/app/360': typeof AuthenticatedApp360Route
  '/app/ai': typeof AuthenticatedAppAiRoute
  '/app/consciencia': typeof AuthenticatedAppConscienciaRoute
  '/app/evolution': typeof AuthenticatedAppEvolutionRoute
  '/app/feedbacks': typeof AuthenticatedAppFeedbacksRoute
  '/app/help': typeof AuthenticatedAppHelpRoute
  '/app/indicators': typeof AuthenticatedAppIndicatorsRoute
  '/app/one-on-ones': typeof AuthenticatedAppOneOnOnesRoute
  '/app/organization': typeof AuthenticatedAppOrganizationRouteWithChildren
  '/app/pdis': typeof AuthenticatedAppPdisRoute
  '/app/pulses': typeof AuthenticatedAppPulsesRoute
  '/app/team': typeof AuthenticatedAppTeamRouteWithChildren
  '/company/billing': typeof AuthenticatedCompanyBillingRoute
  '/company/leaders': typeof AuthenticatedCompanyLeadersRoute
  '/company/leadership': typeof AuthenticatedCompanyLeadershipRoute
  '/company/members': typeof AuthenticatedCompanyMembersRoute
  '/franchise/billing': typeof AuthenticatedFranchiseBillingRoute
  '/franchise/companies': typeof AuthenticatedFranchiseCompaniesRoute
  '/franchise/members': typeof AuthenticatedFranchiseMembersRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/app/': typeof AuthenticatedAppIndexRoute
  '/company/': typeof AuthenticatedCompanyIndexRoute
  '/franchise/': typeof AuthenticatedFranchiseIndexRoute
  '/app/organization/agenda': typeof AuthenticatedAppOrganizationAgendaRoute
  '/app/organization/areas': typeof AuthenticatedAppOrganizationAreasRoute
  '/app/organization/cycles': typeof AuthenticatedAppOrganizationCyclesRoute
  '/app/organization/decisions': typeof AuthenticatedAppOrganizationDecisionsRoute
  '/app/organization/delegations': typeof AuthenticatedAppOrganizationDelegationsRoute
  '/app/organization/documents': typeof AuthenticatedAppOrganizationDocumentsRoute
  '/app/organization/map': typeof AuthenticatedAppOrganizationMapRoute
  '/app/organization/rituals': typeof AuthenticatedAppOrganizationRitualsRoute
  '/app/organization/roles': typeof AuthenticatedAppOrganizationRolesRoute
  '/app/team/$membershipId': typeof AuthenticatedAppTeamMembershipIdRoute
  '/app/organization/': typeof AuthenticatedAppOrganizationIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/p/$token': typeof PTokenRoute
  '/admin/ai': typeof AuthenticatedAdminAiRoute
  '/admin/apps': typeof AuthenticatedAdminAppsRoute
  '/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/admin/branding': typeof AuthenticatedAdminBrandingRoute
  '/admin/data': typeof AuthenticatedAdminDataRoute
  '/admin/franchises': typeof AuthenticatedAdminFranchisesRoute
  '/admin/help': typeof AuthenticatedAdminHelpRoute
  '/admin/hierarchy': typeof AuthenticatedAdminHierarchyRoute
  '/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/admin/licenses': typeof AuthenticatedAdminLicensesRoute
  '/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/admin/methodology': typeof AuthenticatedAdminMethodologyRoute
  '/admin/modules': typeof AuthenticatedAdminModulesRoute
  '/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/admin/onboarding': typeof AuthenticatedAdminOnboardingRoute
  '/admin/organizations': typeof AuthenticatedAdminOrganizationsRoute
  '/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/admin/users': typeof AuthenticatedAdminUsersRoute
  '/app/360': typeof AuthenticatedApp360Route
  '/app/ai': typeof AuthenticatedAppAiRoute
  '/app/consciencia': typeof AuthenticatedAppConscienciaRoute
  '/app/evolution': typeof AuthenticatedAppEvolutionRoute
  '/app/feedbacks': typeof AuthenticatedAppFeedbacksRoute
  '/app/help': typeof AuthenticatedAppHelpRoute
  '/app/indicators': typeof AuthenticatedAppIndicatorsRoute
  '/app/one-on-ones': typeof AuthenticatedAppOneOnOnesRoute
  '/app/pdis': typeof AuthenticatedAppPdisRoute
  '/app/pulses': typeof AuthenticatedAppPulsesRoute
  '/app/team': typeof AuthenticatedAppTeamRouteWithChildren
  '/company/billing': typeof AuthenticatedCompanyBillingRoute
  '/company/leaders': typeof AuthenticatedCompanyLeadersRoute
  '/company/leadership': typeof AuthenticatedCompanyLeadershipRoute
  '/company/members': typeof AuthenticatedCompanyMembersRoute
  '/franchise/billing': typeof AuthenticatedFranchiseBillingRoute
  '/franchise/companies': typeof AuthenticatedFranchiseCompaniesRoute
  '/franchise/members': typeof AuthenticatedFranchiseMembersRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/app': typeof AuthenticatedAppIndexRoute
  '/company': typeof AuthenticatedCompanyIndexRoute
  '/franchise': typeof AuthenticatedFranchiseIndexRoute
  '/app/organization/agenda': typeof AuthenticatedAppOrganizationAgendaRoute
  '/app/organization/areas': typeof AuthenticatedAppOrganizationAreasRoute
  '/app/organization/cycles': typeof AuthenticatedAppOrganizationCyclesRoute
  '/app/organization/decisions': typeof AuthenticatedAppOrganizationDecisionsRoute
  '/app/organization/delegations': typeof AuthenticatedAppOrganizationDelegationsRoute
  '/app/organization/documents': typeof AuthenticatedAppOrganizationDocumentsRoute
  '/app/organization/map': typeof AuthenticatedAppOrganizationMapRoute
  '/app/organization/rituals': typeof AuthenticatedAppOrganizationRitualsRoute
  '/app/organization/roles': typeof AuthenticatedAppOrganizationRolesRoute
  '/app/team/$membershipId': typeof AuthenticatedAppTeamMembershipIdRoute
  '/app/organization': typeof AuthenticatedAppOrganizationIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/app': typeof AuthenticatedAppRouteWithChildren
  '/_authenticated/company': typeof AuthenticatedCompanyRouteWithChildren
  '/_authenticated/franchise': typeof AuthenticatedFranchiseRouteWithChildren
  '/p/$token': typeof PTokenRoute
  '/_authenticated/admin/ai': typeof AuthenticatedAdminAiRoute
  '/_authenticated/admin/apps': typeof AuthenticatedAdminAppsRoute
  '/_authenticated/admin/billing': typeof AuthenticatedAdminBillingRoute
  '/_authenticated/admin/branding': typeof AuthenticatedAdminBrandingRoute
  '/_authenticated/admin/data': typeof AuthenticatedAdminDataRoute
  '/_authenticated/admin/franchises': typeof AuthenticatedAdminFranchisesRoute
  '/_authenticated/admin/help': typeof AuthenticatedAdminHelpRoute
  '/_authenticated/admin/hierarchy': typeof AuthenticatedAdminHierarchyRoute
  '/_authenticated/admin/invoices': typeof AuthenticatedAdminInvoicesRoute
  '/_authenticated/admin/licenses': typeof AuthenticatedAdminLicensesRoute
  '/_authenticated/admin/logs': typeof AuthenticatedAdminLogsRoute
  '/_authenticated/admin/methodology': typeof AuthenticatedAdminMethodologyRoute
  '/_authenticated/admin/modules': typeof AuthenticatedAdminModulesRoute
  '/_authenticated/admin/notifications': typeof AuthenticatedAdminNotificationsRoute
  '/_authenticated/admin/onboarding': typeof AuthenticatedAdminOnboardingRoute
  '/_authenticated/admin/organizations': typeof AuthenticatedAdminOrganizationsRoute
  '/_authenticated/admin/permissions': typeof AuthenticatedAdminPermissionsRoute
  '/_authenticated/admin/plans': typeof AuthenticatedAdminPlansRoute
  '/_authenticated/admin/settings': typeof AuthenticatedAdminSettingsRoute
  '/_authenticated/admin/subscriptions': typeof AuthenticatedAdminSubscriptionsRoute
  '/_authenticated/admin/users': typeof AuthenticatedAdminUsersRoute
  '/_authenticated/app/360': typeof AuthenticatedApp360Route
  '/_authenticated/app/ai': typeof AuthenticatedAppAiRoute
  '/_authenticated/app/consciencia': typeof AuthenticatedAppConscienciaRoute
  '/_authenticated/app/evolution': typeof AuthenticatedAppEvolutionRoute
  '/_authenticated/app/feedbacks': typeof AuthenticatedAppFeedbacksRoute
  '/_authenticated/app/help': typeof AuthenticatedAppHelpRoute
  '/_authenticated/app/indicators': typeof AuthenticatedAppIndicatorsRoute
  '/_authenticated/app/one-on-ones': typeof AuthenticatedAppOneOnOnesRoute
  '/_authenticated/app/organization': typeof AuthenticatedAppOrganizationRouteWithChildren
  '/_authenticated/app/pdis': typeof AuthenticatedAppPdisRoute
  '/_authenticated/app/pulses': typeof AuthenticatedAppPulsesRoute
  '/_authenticated/app/team': typeof AuthenticatedAppTeamRouteWithChildren
  '/_authenticated/company/billing': typeof AuthenticatedCompanyBillingRoute
  '/_authenticated/company/leaders': typeof AuthenticatedCompanyLeadersRoute
  '/_authenticated/company/leadership': typeof AuthenticatedCompanyLeadershipRoute
  '/_authenticated/company/members': typeof AuthenticatedCompanyMembersRoute
  '/_authenticated/franchise/billing': typeof AuthenticatedFranchiseBillingRoute
  '/_authenticated/franchise/companies': typeof AuthenticatedFranchiseCompaniesRoute
  '/_authenticated/franchise/members': typeof AuthenticatedFranchiseMembersRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/app/': typeof AuthenticatedAppIndexRoute
  '/_authenticated/company/': typeof AuthenticatedCompanyIndexRoute
  '/_authenticated/franchise/': typeof AuthenticatedFranchiseIndexRoute
  '/_authenticated/app/organization/agenda': typeof AuthenticatedAppOrganizationAgendaRoute
  '/_authenticated/app/organization/areas': typeof AuthenticatedAppOrganizationAreasRoute
  '/_authenticated/app/organization/cycles': typeof AuthenticatedAppOrganizationCyclesRoute
  '/_authenticated/app/organization/decisions': typeof AuthenticatedAppOrganizationDecisionsRoute
  '/_authenticated/app/organization/delegations': typeof AuthenticatedAppOrganizationDelegationsRoute
  '/_authenticated/app/organization/documents': typeof AuthenticatedAppOrganizationDocumentsRoute
  '/_authenticated/app/organization/map': typeof AuthenticatedAppOrganizationMapRoute
  '/_authenticated/app/organization/rituals': typeof AuthenticatedAppOrganizationRitualsRoute
  '/_authenticated/app/organization/roles': typeof AuthenticatedAppOrganizationRolesRoute
  '/_authenticated/app/team/$membershipId': typeof AuthenticatedAppTeamMembershipIdRoute
  '/_authenticated/app/organization/': typeof AuthenticatedAppOrganizationIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/app'
    | '/company'
    | '/franchise'
    | '/p/$token'
    | '/admin/ai'
    | '/admin/apps'
    | '/admin/billing'
    | '/admin/branding'
    | '/admin/data'
    | '/admin/franchises'
    | '/admin/help'
    | '/admin/hierarchy'
    | '/admin/invoices'
    | '/admin/licenses'
    | '/admin/logs'
    | '/admin/methodology'
    | '/admin/modules'
    | '/admin/notifications'
    | '/admin/onboarding'
    | '/admin/organizations'
    | '/admin/permissions'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/app/360'
    | '/app/ai'
    | '/app/consciencia'
    | '/app/evolution'
    | '/app/feedbacks'
    | '/app/help'
    | '/app/indicators'
    | '/app/one-on-ones'
    | '/app/organization'
    | '/app/pdis'
    | '/app/pulses'
    | '/app/team'
    | '/company/billing'
    | '/company/leaders'
    | '/company/leadership'
    | '/company/members'
    | '/franchise/billing'
    | '/franchise/companies'
    | '/franchise/members'
    | '/admin/'
    | '/app/'
    | '/company/'
    | '/franchise/'
    | '/app/organization/agenda'
    | '/app/organization/areas'
    | '/app/organization/cycles'
    | '/app/organization/decisions'
    | '/app/organization/delegations'
    | '/app/organization/documents'
    | '/app/organization/map'
    | '/app/organization/rituals'
    | '/app/organization/roles'
    | '/app/team/$membershipId'
    | '/app/organization/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/p/$token'
    | '/admin/ai'
    | '/admin/apps'
    | '/admin/billing'
    | '/admin/branding'
    | '/admin/data'
    | '/admin/franchises'
    | '/admin/help'
    | '/admin/hierarchy'
    | '/admin/invoices'
    | '/admin/licenses'
    | '/admin/logs'
    | '/admin/methodology'
    | '/admin/modules'
    | '/admin/notifications'
    | '/admin/onboarding'
    | '/admin/organizations'
    | '/admin/permissions'
    | '/admin/plans'
    | '/admin/settings'
    | '/admin/subscriptions'
    | '/admin/users'
    | '/app/360'
    | '/app/ai'
    | '/app/consciencia'
    | '/app/evolution'
    | '/app/feedbacks'
    | '/app/help'
    | '/app/indicators'
    | '/app/one-on-ones'
    | '/app/pdis'
    | '/app/pulses'
    | '/app/team'
    | '/company/billing'
    | '/company/leaders'
    | '/company/leadership'
    | '/company/members'
    | '/franchise/billing'
    | '/franchise/companies'
    | '/franchise/members'
    | '/admin'
    | '/app'
    | '/company'
    | '/franchise'
    | '/app/organization/agenda'
    | '/app/organization/areas'
    | '/app/organization/cycles'
    | '/app/organization/decisions'
    | '/app/organization/delegations'
    | '/app/organization/documents'
    | '/app/organization/map'
    | '/app/organization/rituals'
    | '/app/organization/roles'
    | '/app/team/$membershipId'
    | '/app/organization'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/app'
    | '/_authenticated/company'
    | '/_authenticated/franchise'
    | '/p/$token'
    | '/_authenticated/admin/ai'
    | '/_authenticated/admin/apps'
    | '/_authenticated/admin/billing'
    | '/_authenticated/admin/branding'
    | '/_authenticated/admin/data'
    | '/_authenticated/admin/franchises'
    | '/_authenticated/admin/help'
    | '/_authenticated/admin/hierarchy'
    | '/_authenticated/admin/invoices'
    | '/_authenticated/admin/licenses'
    | '/_authenticated/admin/logs'
    | '/_authenticated/admin/methodology'
    | '/_authenticated/admin/modules'
    | '/_authenticated/admin/notifications'
    | '/_authenticated/admin/onboarding'
    | '/_authenticated/admin/organizations'
    | '/_authenticated/admin/permissions'
    | '/_authenticated/admin/plans'
    | '/_authenticated/admin/settings'
    | '/_authenticated/admin/subscriptions'
    | '/_authenticated/admin/users'
    | '/_authenticated/app/360'
    | '/_authenticated/app/ai'
    | '/_authenticated/app/consciencia'
    | '/_authenticated/app/evolution'
    | '/_authenticated/app/feedbacks'
    | '/_authenticated/app/help'
    | '/_authenticated/app/indicators'
    | '/_authenticated/app/one-on-ones'
    | '/_authenticated/app/organization'
    | '/_authenticated/app/pdis'
    | '/_authenticated/app/pulses'
    | '/_authenticated/app/team'
    | '/_authenticated/company/billing'
    | '/_authenticated/company/leaders'
    | '/_authenticated/company/leadership'
    | '/_authenticated/company/members'
    | '/_authenticated/franchise/billing'
    | '/_authenticated/franchise/companies'
    | '/_authenticated/franchise/members'
    | '/_authenticated/admin/'
    | '/_authenticated/app/'
    | '/_authenticated/company/'
    | '/_authenticated/franchise/'
    | '/_authenticated/app/organization/agenda'
    | '/_authenticated/app/organization/areas'
    | '/_authenticated/app/organization/cycles'
    | '/_authenticated/app/organization/decisions'
    | '/_authenticated/app/organization/delegations'
    | '/_authenticated/app/organization/documents'
    | '/_authenticated/app/organization/map'
    | '/_authenticated/app/organization/rituals'
    | '/_authenticated/app/organization/roles'
    | '/_authenticated/app/team/$membershipId'
    | '/_authenticated/app/organization/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  PTokenRoute: typeof PTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/p/$token': {
      id: '/p/$token'
      path: '/p/$token'
      fullPath: '/p/$token'
      preLoaderRoute: typeof PTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/franchise': {
      id: '/_authenticated/franchise'
      path: '/franchise'
      fullPath: '/franchise'
      preLoaderRoute: typeof AuthenticatedFranchiseRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/company': {
      id: '/_authenticated/company'
      path: '/company'
      fullPath: '/company'
      preLoaderRoute: typeof AuthenticatedCompanyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/app': {
      id: '/_authenticated/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AuthenticatedAppRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/franchise/': {
      id: '/_authenticated/franchise/'
      path: '/'
      fullPath: '/franchise/'
      preLoaderRoute: typeof AuthenticatedFranchiseIndexRouteImport
      parentRoute: typeof AuthenticatedFranchiseRoute
    }
    '/_authenticated/company/': {
      id: '/_authenticated/company/'
      path: '/'
      fullPath: '/company/'
      preLoaderRoute: typeof AuthenticatedCompanyIndexRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/app/': {
      id: '/_authenticated/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AuthenticatedAppIndexRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/franchise/members': {
      id: '/_authenticated/franchise/members'
      path: '/members'
      fullPath: '/franchise/members'
      preLoaderRoute: typeof AuthenticatedFranchiseMembersRouteImport
      parentRoute: typeof AuthenticatedFranchiseRoute
    }
    '/_authenticated/franchise/companies': {
      id: '/_authenticated/franchise/companies'
      path: '/companies'
      fullPath: '/franchise/companies'
      preLoaderRoute: typeof AuthenticatedFranchiseCompaniesRouteImport
      parentRoute: typeof AuthenticatedFranchiseRoute
    }
    '/_authenticated/franchise/billing': {
      id: '/_authenticated/franchise/billing'
      path: '/billing'
      fullPath: '/franchise/billing'
      preLoaderRoute: typeof AuthenticatedFranchiseBillingRouteImport
      parentRoute: typeof AuthenticatedFranchiseRoute
    }
    '/_authenticated/company/members': {
      id: '/_authenticated/company/members'
      path: '/members'
      fullPath: '/company/members'
      preLoaderRoute: typeof AuthenticatedCompanyMembersRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/company/leadership': {
      id: '/_authenticated/company/leadership'
      path: '/leadership'
      fullPath: '/company/leadership'
      preLoaderRoute: typeof AuthenticatedCompanyLeadershipRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/company/leaders': {
      id: '/_authenticated/company/leaders'
      path: '/leaders'
      fullPath: '/company/leaders'
      preLoaderRoute: typeof AuthenticatedCompanyLeadersRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/company/billing': {
      id: '/_authenticated/company/billing'
      path: '/billing'
      fullPath: '/company/billing'
      preLoaderRoute: typeof AuthenticatedCompanyBillingRouteImport
      parentRoute: typeof AuthenticatedCompanyRoute
    }
    '/_authenticated/app/team': {
      id: '/_authenticated/app/team'
      path: '/team'
      fullPath: '/app/team'
      preLoaderRoute: typeof AuthenticatedAppTeamRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/pulses': {
      id: '/_authenticated/app/pulses'
      path: '/pulses'
      fullPath: '/app/pulses'
      preLoaderRoute: typeof AuthenticatedAppPulsesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/pdis': {
      id: '/_authenticated/app/pdis'
      path: '/pdis'
      fullPath: '/app/pdis'
      preLoaderRoute: typeof AuthenticatedAppPdisRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/organization': {
      id: '/_authenticated/app/organization'
      path: '/organization'
      fullPath: '/app/organization'
      preLoaderRoute: typeof AuthenticatedAppOrganizationRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/one-on-ones': {
      id: '/_authenticated/app/one-on-ones'
      path: '/one-on-ones'
      fullPath: '/app/one-on-ones'
      preLoaderRoute: typeof AuthenticatedAppOneOnOnesRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/indicators': {
      id: '/_authenticated/app/indicators'
      path: '/indicators'
      fullPath: '/app/indicators'
      preLoaderRoute: typeof AuthenticatedAppIndicatorsRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/help': {
      id: '/_authenticated/app/help'
      path: '/help'
      fullPath: '/app/help'
      preLoaderRoute: typeof AuthenticatedAppHelpRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/feedbacks': {
      id: '/_authenticated/app/feedbacks'
      path: '/feedbacks'
      fullPath: '/app/feedbacks'
      preLoaderRoute: typeof AuthenticatedAppFeedbacksRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/evolution': {
      id: '/_authenticated/app/evolution'
      path: '/evolution'
      fullPath: '/app/evolution'
      preLoaderRoute: typeof AuthenticatedAppEvolutionRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/consciencia': {
      id: '/_authenticated/app/consciencia'
      path: '/consciencia'
      fullPath: '/app/consciencia'
      preLoaderRoute: typeof AuthenticatedAppConscienciaRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/ai': {
      id: '/_authenticated/app/ai'
      path: '/ai'
      fullPath: '/app/ai'
      preLoaderRoute: typeof AuthenticatedAppAiRouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/app/360': {
      id: '/_authenticated/app/360'
      path: '/360'
      fullPath: '/app/360'
      preLoaderRoute: typeof AuthenticatedApp360RouteImport
      parentRoute: typeof AuthenticatedAppRoute
    }
    '/_authenticated/admin/users': {
      id: '/_authenticated/admin/users'
      path: '/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/subscriptions': {
      id: '/_authenticated/admin/subscriptions'
      path: '/subscriptions'
      fullPath: '/admin/subscriptions'
      preLoaderRoute: typeof AuthenticatedAdminSubscriptionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/settings': {
      id: '/_authenticated/admin/settings'
      path: '/settings'
      fullPath: '/admin/settings'
      preLoaderRoute: typeof AuthenticatedAdminSettingsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/plans': {
      id: '/_authenticated/admin/plans'
      path: '/plans'
      fullPath: '/admin/plans'
      preLoaderRoute: typeof AuthenticatedAdminPlansRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/permissions': {
      id: '/_authenticated/admin/permissions'
      path: '/permissions'
      fullPath: '/admin/permissions'
      preLoaderRoute: typeof AuthenticatedAdminPermissionsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/organizations': {
      id: '/_authenticated/admin/organizations'
      path: '/organizations'
      fullPath: '/admin/organizations'
      preLoaderRoute: typeof AuthenticatedAdminOrganizationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/onboarding': {
      id: '/_authenticated/admin/onboarding'
      path: '/onboarding'
      fullPath: '/admin/onboarding'
      preLoaderRoute: typeof AuthenticatedAdminOnboardingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/notifications': {
      id: '/_authenticated/admin/notifications'
      path: '/notifications'
      fullPath: '/admin/notifications'
      preLoaderRoute: typeof AuthenticatedAdminNotificationsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/modules': {
      id: '/_authenticated/admin/modules'
      path: '/modules'
      fullPath: '/admin/modules'
      preLoaderRoute: typeof AuthenticatedAdminModulesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/methodology': {
      id: '/_authenticated/admin/methodology'
      path: '/methodology'
      fullPath: '/admin/methodology'
      preLoaderRoute: typeof AuthenticatedAdminMethodologyRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/logs': {
      id: '/_authenticated/admin/logs'
      path: '/logs'
      fullPath: '/admin/logs'
      preLoaderRoute: typeof AuthenticatedAdminLogsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/licenses': {
      id: '/_authenticated/admin/licenses'
      path: '/licenses'
      fullPath: '/admin/licenses'
      preLoaderRoute: typeof AuthenticatedAdminLicensesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/invoices': {
      id: '/_authenticated/admin/invoices'
      path: '/invoices'
      fullPath: '/admin/invoices'
      preLoaderRoute: typeof AuthenticatedAdminInvoicesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/hierarchy': {
      id: '/_authenticated/admin/hierarchy'
      path: '/hierarchy'
      fullPath: '/admin/hierarchy'
      preLoaderRoute: typeof AuthenticatedAdminHierarchyRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/help': {
      id: '/_authenticated/admin/help'
      path: '/help'
      fullPath: '/admin/help'
      preLoaderRoute: typeof AuthenticatedAdminHelpRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/franchises': {
      id: '/_authenticated/admin/franchises'
      path: '/franchises'
      fullPath: '/admin/franchises'
      preLoaderRoute: typeof AuthenticatedAdminFranchisesRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/data': {
      id: '/_authenticated/admin/data'
      path: '/data'
      fullPath: '/admin/data'
      preLoaderRoute: typeof AuthenticatedAdminDataRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/branding': {
      id: '/_authenticated/admin/branding'
      path: '/branding'
      fullPath: '/admin/branding'
      preLoaderRoute: typeof AuthenticatedAdminBrandingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/billing': {
      id: '/_authenticated/admin/billing'
      path: '/billing'
      fullPath: '/admin/billing'
      preLoaderRoute: typeof AuthenticatedAdminBillingRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/apps': {
      id: '/_authenticated/admin/apps'
      path: '/apps'
      fullPath: '/admin/apps'
      preLoaderRoute: typeof AuthenticatedAdminAppsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/ai': {
      id: '/_authenticated/admin/ai'
      path: '/ai'
      fullPath: '/admin/ai'
      preLoaderRoute: typeof AuthenticatedAdminAiRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/app/organization/': {
      id: '/_authenticated/app/organization/'
      path: '/'
      fullPath: '/app/organization/'
      preLoaderRoute: typeof AuthenticatedAppOrganizationIndexRouteImport
      parentRoute: typeof AuthenticatedAppOrganizationRoute
    }
    '/_authenticated/app/team/$membershipId': {
      id: '/_authenticated/app/team/$membershipId'
      path: '/$membershipId'
      fullPath: '/app/team/$membershipId'
      preLoaderRoute: typeof AuthenticatedAppTeamMembershipIdRouteImport
      parentRoute: typeof AuthenticatedAppTeamRoute
    }
    '/_authenticated/app/organization/roles': {
      id: '/_authenticated/app/organization/roles'
      path: '/roles'
      fullPath: '/app/organization/roles'
      preLoaderRoute: typeof AuthenticatedAppOrganizationRolesRouteImport
      parentRoute: typeof AuthenticatedAppOrganizationRoute
    }
    '/_authenticated/app/organization/rituals': {
      id: '/_authenticated/app/organization/rituals'
      path: '/rituals'
      fullPath: '/app/organization/rituals'
      preLoaderRoute: typeof AuthenticatedAppOrganizationRitualsRouteImport
      parentRoute: typeof AuthenticatedAppOrganizationRoute
    }
    '/_authenticated/app/organization/map': {
      id: '/_authenticated/app/organization/map'
      path: '/map'
      fullPath: '/app/organization/map'
      preLoaderRoute: typeof AuthenticatedAppOrganizationMapRouteImport
      parentRoute: typeof AuthenticatedAppOrganizationRoute
    }
    '/_authenticated/app/organization/documents': {
      id: '/_authenticated/app/organization/documents'
      path: '/documents'
      fullPath: '/app/organization/documents'
      preLoaderRoute: typeof AuthenticatedAppOrganizationDocumentsRouteImport
      parentRoute: typeof AuthenticatedAppOrganizationRoute
    }
    '/_authenticated/app/organization/delegations': {
      id: '/_authenticated/app/organization/delegations'
      path: '/delegations'
      fullPath: '/app/organization/delegations'
      preLoaderRoute: typeof AuthenticatedAppOrganizationDelegationsRouteImport
      parentRoute: typeof AuthenticatedAppOrganizationRoute
    }
    '/_authenticated/app/organization/decisions': {
      id: '/_authenticated/app/organization/decisions'
      path: '/decisions'
      fullPath: '/app/organization/decisions'
      preLoaderRoute: typeof AuthenticatedAppOrganizationDecisionsRouteImport
      parentRoute: typeof AuthenticatedAppOrganizationRoute
    }
    '/_authenticated/app/organization/cycles': {
      id: '/_authenticated/app/organization/cycles'
      path: '/cycles'
      fullPath: '/app/organization/cycles'
      preLoaderRoute: typeof AuthenticatedAppOrganizationCyclesRouteImport
      parentRoute: typeof AuthenticatedAppOrganizationRoute
    }
    '/_authenticated/app/organization/areas': {
      id: '/_authenticated/app/organization/areas'
      path: '/areas'
      fullPath: '/app/organization/areas'
      preLoaderRoute: typeof AuthenticatedAppOrganizationAreasRouteImport
      parentRoute: typeof AuthenticatedAppOrganizationRoute
    }
    '/_authenticated/app/organization/agenda': {
      id: '/_authenticated/app/organization/agenda'
      path: '/agenda'
      fullPath: '/app/organization/agenda'
      preLoaderRoute: typeof AuthenticatedAppOrganizationAgendaRouteImport
      parentRoute: typeof AuthenticatedAppOrganizationRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAiRoute: typeof AuthenticatedAdminAiRoute
  AuthenticatedAdminAppsRoute: typeof AuthenticatedAdminAppsRoute
  AuthenticatedAdminBillingRoute: typeof AuthenticatedAdminBillingRoute
  AuthenticatedAdminBrandingRoute: typeof AuthenticatedAdminBrandingRoute
  AuthenticatedAdminDataRoute: typeof AuthenticatedAdminDataRoute
  AuthenticatedAdminFranchisesRoute: typeof AuthenticatedAdminFranchisesRoute
  AuthenticatedAdminHelpRoute: typeof AuthenticatedAdminHelpRoute
  AuthenticatedAdminHierarchyRoute: typeof AuthenticatedAdminHierarchyRoute
  AuthenticatedAdminInvoicesRoute: typeof AuthenticatedAdminInvoicesRoute
  AuthenticatedAdminLicensesRoute: typeof AuthenticatedAdminLicensesRoute
  AuthenticatedAdminLogsRoute: typeof AuthenticatedAdminLogsRoute
  AuthenticatedAdminMethodologyRoute: typeof AuthenticatedAdminMethodologyRoute
  AuthenticatedAdminModulesRoute: typeof AuthenticatedAdminModulesRoute
  AuthenticatedAdminNotificationsRoute: typeof AuthenticatedAdminNotificationsRoute
  AuthenticatedAdminOnboardingRoute: typeof AuthenticatedAdminOnboardingRoute
  AuthenticatedAdminOrganizationsRoute: typeof AuthenticatedAdminOrganizationsRoute
  AuthenticatedAdminPermissionsRoute: typeof AuthenticatedAdminPermissionsRoute
  AuthenticatedAdminPlansRoute: typeof AuthenticatedAdminPlansRoute
  AuthenticatedAdminSettingsRoute: typeof AuthenticatedAdminSettingsRoute
  AuthenticatedAdminSubscriptionsRoute: typeof AuthenticatedAdminSubscriptionsRoute
  AuthenticatedAdminUsersRoute: typeof AuthenticatedAdminUsersRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAiRoute: AuthenticatedAdminAiRoute,
  AuthenticatedAdminAppsRoute: AuthenticatedAdminAppsRoute,
  AuthenticatedAdminBillingRoute: AuthenticatedAdminBillingRoute,
  AuthenticatedAdminBrandingRoute: AuthenticatedAdminBrandingRoute,
  AuthenticatedAdminDataRoute: AuthenticatedAdminDataRoute,
  AuthenticatedAdminFranchisesRoute: AuthenticatedAdminFranchisesRoute,
  AuthenticatedAdminHelpRoute: AuthenticatedAdminHelpRoute,
  AuthenticatedAdminHierarchyRoute: AuthenticatedAdminHierarchyRoute,
  AuthenticatedAdminInvoicesRoute: AuthenticatedAdminInvoicesRoute,
  AuthenticatedAdminLicensesRoute: AuthenticatedAdminLicensesRoute,
  AuthenticatedAdminLogsRoute: AuthenticatedAdminLogsRoute,
  AuthenticatedAdminMethodologyRoute: AuthenticatedAdminMethodologyRoute,
  AuthenticatedAdminModulesRoute: AuthenticatedAdminModulesRoute,
  AuthenticatedAdminNotificationsRoute: AuthenticatedAdminNotificationsRoute,
  AuthenticatedAdminOnboardingRoute: AuthenticatedAdminOnboardingRoute,
  AuthenticatedAdminOrganizationsRoute: AuthenticatedAdminOrganizationsRoute,
  AuthenticatedAdminPermissionsRoute: AuthenticatedAdminPermissionsRoute,
  AuthenticatedAdminPlansRoute: AuthenticatedAdminPlansRoute,
  AuthenticatedAdminSettingsRoute: AuthenticatedAdminSettingsRoute,
  AuthenticatedAdminSubscriptionsRoute: AuthenticatedAdminSubscriptionsRoute,
  AuthenticatedAdminUsersRoute: AuthenticatedAdminUsersRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedAppOrganizationRouteChildren {
  AuthenticatedAppOrganizationAgendaRoute: typeof AuthenticatedAppOrganizationAgendaRoute
  AuthenticatedAppOrganizationAreasRoute: typeof AuthenticatedAppOrganizationAreasRoute
  AuthenticatedAppOrganizationCyclesRoute: typeof AuthenticatedAppOrganizationCyclesRoute
  AuthenticatedAppOrganizationDecisionsRoute: typeof AuthenticatedAppOrganizationDecisionsRoute
  AuthenticatedAppOrganizationDelegationsRoute: typeof AuthenticatedAppOrganizationDelegationsRoute
  AuthenticatedAppOrganizationDocumentsRoute: typeof AuthenticatedAppOrganizationDocumentsRoute
  AuthenticatedAppOrganizationMapRoute: typeof AuthenticatedAppOrganizationMapRoute
  AuthenticatedAppOrganizationRitualsRoute: typeof AuthenticatedAppOrganizationRitualsRoute
  AuthenticatedAppOrganizationRolesRoute: typeof AuthenticatedAppOrganizationRolesRoute
  AuthenticatedAppOrganizationIndexRoute: typeof AuthenticatedAppOrganizationIndexRoute
}

const AuthenticatedAppOrganizationRouteChildren: AuthenticatedAppOrganizationRouteChildren =
  {
    AuthenticatedAppOrganizationAgendaRoute:
      AuthenticatedAppOrganizationAgendaRoute,
    AuthenticatedAppOrganizationAreasRoute:
      AuthenticatedAppOrganizationAreasRoute,
    AuthenticatedAppOrganizationCyclesRoute:
      AuthenticatedAppOrganizationCyclesRoute,
    AuthenticatedAppOrganizationDecisionsRoute:
      AuthenticatedAppOrganizationDecisionsRoute,
    AuthenticatedAppOrganizationDelegationsRoute:
      AuthenticatedAppOrganizationDelegationsRoute,
    AuthenticatedAppOrganizationDocumentsRoute:
      AuthenticatedAppOrganizationDocumentsRoute,
    AuthenticatedAppOrganizationMapRoute: AuthenticatedAppOrganizationMapRoute,
    AuthenticatedAppOrganizationRitualsRoute:
      AuthenticatedAppOrganizationRitualsRoute,
    AuthenticatedAppOrganizationRolesRoute:
      AuthenticatedAppOrganizationRolesRoute,
    AuthenticatedAppOrganizationIndexRoute:
      AuthenticatedAppOrganizationIndexRoute,
  }

const AuthenticatedAppOrganizationRouteWithChildren =
  AuthenticatedAppOrganizationRoute._addFileChildren(
    AuthenticatedAppOrganizationRouteChildren,
  )

interface AuthenticatedAppTeamRouteChildren {
  AuthenticatedAppTeamMembershipIdRoute: typeof AuthenticatedAppTeamMembershipIdRoute
}

const AuthenticatedAppTeamRouteChildren: AuthenticatedAppTeamRouteChildren = {
  AuthenticatedAppTeamMembershipIdRoute: AuthenticatedAppTeamMembershipIdRoute,
}

const AuthenticatedAppTeamRouteWithChildren =
  AuthenticatedAppTeamRoute._addFileChildren(AuthenticatedAppTeamRouteChildren)

interface AuthenticatedAppRouteChildren {
  AuthenticatedApp360Route: typeof AuthenticatedApp360Route
  AuthenticatedAppAiRoute: typeof AuthenticatedAppAiRoute
  AuthenticatedAppConscienciaRoute: typeof AuthenticatedAppConscienciaRoute
  AuthenticatedAppEvolutionRoute: typeof AuthenticatedAppEvolutionRoute
  AuthenticatedAppFeedbacksRoute: typeof AuthenticatedAppFeedbacksRoute
  AuthenticatedAppHelpRoute: typeof AuthenticatedAppHelpRoute
  AuthenticatedAppIndicatorsRoute: typeof AuthenticatedAppIndicatorsRoute
  AuthenticatedAppOneOnOnesRoute: typeof AuthenticatedAppOneOnOnesRoute
  AuthenticatedAppOrganizationRoute: typeof AuthenticatedAppOrganizationRouteWithChildren
  AuthenticatedAppPdisRoute: typeof AuthenticatedAppPdisRoute
  AuthenticatedAppPulsesRoute: typeof AuthenticatedAppPulsesRoute
  AuthenticatedAppTeamRoute: typeof AuthenticatedAppTeamRouteWithChildren
  AuthenticatedAppIndexRoute: typeof AuthenticatedAppIndexRoute
}

const AuthenticatedAppRouteChildren: AuthenticatedAppRouteChildren = {
  AuthenticatedApp360Route: AuthenticatedApp360Route,
  AuthenticatedAppAiRoute: AuthenticatedAppAiRoute,
  AuthenticatedAppConscienciaRoute: AuthenticatedAppConscienciaRoute,
  AuthenticatedAppEvolutionRoute: AuthenticatedAppEvolutionRoute,
  AuthenticatedAppFeedbacksRoute: AuthenticatedAppFeedbacksRoute,
  AuthenticatedAppHelpRoute: AuthenticatedAppHelpRoute,
  AuthenticatedAppIndicatorsRoute: AuthenticatedAppIndicatorsRoute,
  AuthenticatedAppOneOnOnesRoute: AuthenticatedAppOneOnOnesRoute,
  AuthenticatedAppOrganizationRoute:
    AuthenticatedAppOrganizationRouteWithChildren,
  AuthenticatedAppPdisRoute: AuthenticatedAppPdisRoute,
  AuthenticatedAppPulsesRoute: AuthenticatedAppPulsesRoute,
  AuthenticatedAppTeamRoute: AuthenticatedAppTeamRouteWithChildren,
  AuthenticatedAppIndexRoute: AuthenticatedAppIndexRoute,
}

const AuthenticatedAppRouteWithChildren =
  AuthenticatedAppRoute._addFileChildren(AuthenticatedAppRouteChildren)

interface AuthenticatedCompanyRouteChildren {
  AuthenticatedCompanyBillingRoute: typeof AuthenticatedCompanyBillingRoute
  AuthenticatedCompanyLeadersRoute: typeof AuthenticatedCompanyLeadersRoute
  AuthenticatedCompanyLeadershipRoute: typeof AuthenticatedCompanyLeadershipRoute
  AuthenticatedCompanyMembersRoute: typeof AuthenticatedCompanyMembersRoute
  AuthenticatedCompanyIndexRoute: typeof AuthenticatedCompanyIndexRoute
}

const AuthenticatedCompanyRouteChildren: AuthenticatedCompanyRouteChildren = {
  AuthenticatedCompanyBillingRoute: AuthenticatedCompanyBillingRoute,
  AuthenticatedCompanyLeadersRoute: AuthenticatedCompanyLeadersRoute,
  AuthenticatedCompanyLeadershipRoute: AuthenticatedCompanyLeadershipRoute,
  AuthenticatedCompanyMembersRoute: AuthenticatedCompanyMembersRoute,
  AuthenticatedCompanyIndexRoute: AuthenticatedCompanyIndexRoute,
}

const AuthenticatedCompanyRouteWithChildren =
  AuthenticatedCompanyRoute._addFileChildren(AuthenticatedCompanyRouteChildren)

interface AuthenticatedFranchiseRouteChildren {
  AuthenticatedFranchiseBillingRoute: typeof AuthenticatedFranchiseBillingRoute
  AuthenticatedFranchiseCompaniesRoute: typeof AuthenticatedFranchiseCompaniesRoute
  AuthenticatedFranchiseMembersRoute: typeof AuthenticatedFranchiseMembersRoute
  AuthenticatedFranchiseIndexRoute: typeof AuthenticatedFranchiseIndexRoute
}

const AuthenticatedFranchiseRouteChildren: AuthenticatedFranchiseRouteChildren =
  {
    AuthenticatedFranchiseBillingRoute: AuthenticatedFranchiseBillingRoute,
    AuthenticatedFranchiseCompaniesRoute: AuthenticatedFranchiseCompaniesRoute,
    AuthenticatedFranchiseMembersRoute: AuthenticatedFranchiseMembersRoute,
    AuthenticatedFranchiseIndexRoute: AuthenticatedFranchiseIndexRoute,
  }

const AuthenticatedFranchiseRouteWithChildren =
  AuthenticatedFranchiseRoute._addFileChildren(
    AuthenticatedFranchiseRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedAppRoute: typeof AuthenticatedAppRouteWithChildren
  AuthenticatedCompanyRoute: typeof AuthenticatedCompanyRouteWithChildren
  AuthenticatedFranchiseRoute: typeof AuthenticatedFranchiseRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedAppRoute: AuthenticatedAppRouteWithChildren,
  AuthenticatedCompanyRoute: AuthenticatedCompanyRouteWithChildren,
  AuthenticatedFranchiseRoute: AuthenticatedFranchiseRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  PTokenRoute: PTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
